### ISSUE TITLE
Feedback Iteração0

### ISSUE THREAD

**Issue by lsca** [IF977/InPolitica#11]
Fala galera,

Vê só, passando aqui só para dar o feedback da iteração0 de vocês, qualquer duvida só comentar por aqui ou no slack.

Histórias de Usuários : 10
Ata da reunião com cliente : 10
Mockups e storyboards : 5 + 0 = 5 . (Não encontrei o StoryBoard de vocês, caso tenham colocado aqui no repositório mandem aqui o link que eu reajusto a nota. 
Preenchimento do gitHub : 10
Postmortem : 10

Caso concordem, fechem a issue.

**Comment by vanessa** [comment]
O grupo tá ciente. Valeu!
