### ISSUE TITLE
Correção Cadastrar histórias no gitHub Iteração1

### ISSUE THREAD

**Issue by lsca** [IF977/InPolitica#19]
Fala galera!

Uso de lable : OK!
Milestones : OK!
1 Issue por participante : OK!
Descrição da issue : -2 .

Nota final: 8

Qualquer duvida só comentar aqui. Caso contrario fechem a issue!

Vlw 👍

**Comment by vanessa** [comment]
Tu pode explicar um pouco mais o que faltou pra tirar 2 pontos, @lsca?

**Comment by vanessa** [comment]
Lembrar de colocar detalhes na criação das issues. Não dar espaço para pessoas de fora terem dúvida sobre o que cada issue é.
