### ISSUE TITLE
FeedBack do Postmortem da interação 01

### ISSUE THREAD

**Issue by Lerissonf** [IF977/InPolitica#29]
## Postmortem
* Atraso do Postmortem -> não, (nota base 10.0)
  - Entregas feitas no até o dia final da iteração (09/10) têm nota base 10;
  - Entregas feitas no até um dia após final da iteração (10/10) têm nota base 8;
  - Entregas feitas no até dois dia após final da iteração (11/10) têm nota base 6;
  - Entregas feitas após dois dias do final da iteração (12/10 em diante) são zeradas.
* O que estava planejado ->ok
* Listar as atividades que foram planejadas para a interação e o responsável por cada uma delas ->
  - Faltou indicar o responsável pelo item "Modelagem do banco de dados"
  - Redução de 1,0%
* O que foi feito -> ok
* O que não foi feito -> ok
 - Faltou indicar o responsável por cada item que não foi realizado
 - Redução de 1,5% 
* O que está planejado pra próxima iteração ->ok
* Listar as atividades que foram planejadas para a próxima interação e o responsável por cada uma delas ->
  - Faltou indicar o responsável por cada item que será realizado para a próxima interação
  - Redução de 1,5%
* Lições aprendidas -> ok
* Formato Markdown -> ok

### nota final: 10 * (100% - (1,0% + 1,5% + 1,5%)) = 9,6
---
### Observações finais:
> Pessoal, reforçando, não esqueçam de atribuir o responsável da atividade.

**Comment by Lerissonf** [comment]
Tinha esquecido de adicionar o feedback.

**Comment by vanessa** [comment]
Grupo ciente.
